- hosts: ansible-practic
  gather_facts: no

  tasks: 
    - name: change index.html
      ansible.builtin.copy:
        src: ../tmp_files/index.html
        dest: /home/ansible-worker/www/stud-template/index.html
        mode: '0644'
      become: yes
      tags: build_repo